from django.urls import path
from .import views

urlpatterns = [
    path("customer/",views.register_customer,name="registration"),
    path("customers/",views.list_customers,name="customers_list"),
    path("customers/<int:id>/",views.customer_profile,name ="customer_profile"),
    path("customers/edit/<int:id>/",views.edit_customer,name="edit_customer"),
    path("wallet/",views.register_wallet,name="wallet"),
    path("wallets/",views.list_wallets,name="wallets_list"),
    path("wallets/<int:id>/",views.wallet_entries,name ="wallet_entries"),
    path("wallets/edit/<int:id>/",views.edit_wallet,name="edit_wallet"),
    path("currency/",views.register_currency,name="currency"),
    path("currencies/",views.list_currencies,name="currencies_list"),
    path("account/",views.register_account,name="account"),
    path("accounts/",views.list_accounts,name="accounts_list"),
    path("accounts/<int:id>/",views.account_details,name ="account_details"),
    path("accounts/edit/<int:id>/",views.edit_account,name="edit_account"),
    path("thirdparty/",views.register_thirdparty,name="third_party"),
    path("thirdparties/",views.list_third_parties,name="third_parties_list"),
    path("receipt/",views.register_receipt,name="receipt"),
    path("receipts/",views.list_receipts,name="receipts_list"),
    path("receipts/<int:id>/",views.receipt_details,name ="receipt_details"),
    path("receipts/edit/<int:id>/",views.edit_receipt,name="edit_receipt"),
    path("transaction/",views.register_transaction,name="transaction"),
    path("transactions/",views.list_transactions,name="transactions_list"),
    path("transactions/<int:id>/",views.transaction_details,name ="transaction_details"),
    path("transactions/edit/<int:id>/",views.edit_transaction,name="edit_transaction"),
    path("card/",views.register_card,name="card"),
    path("cards/",views.list_cards,name="cards_list"),
    path("cards/<int:id>/",views.card_details,name ="card_details"),
    path("cards/edit/<int:id>/",views.edit_card,name="edit_card"),
    path("notification/",views.register_notification,name="notification"),
    path("notifications/",views.list_notifications,name="notifications_list"),
    path("loan/",views.register_loan,name="loan"),
    path("loans/",views.list_loans,name="loans_list"),
    path("reward/",views.register_reward,name="reward"),
    path("rewards/",views.list_rewards,name="rewards_list"),
]