# Generated by Django 4.0.6 on 2022-09-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
    ]
