# Generated by Django 4.0.6 on 2022-09-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_customer_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipt_transaction', to='wallet.receipt'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
